#!/bin/bash

[[ -f ${HOME}/.officeoverlayrc ]] && source ${HOME}/.officeoverlayrc

CVS_PATH="${CVS_PATH:-${HOME}/Gentoo/gentoo-x86}"
OVERLAY_PATH="${OVERLAY_PATH:-${HOME}/Gentoo/office}"

echo cd "${OVERLAY_PATH}"
cd "${OVERLAY_PATH}"

for name in $(
	find . -type f |
		grep -v '/Manifest$' |
		grep -v '/ChangeLog' |
		grep -v '^\./\.git' |
		grep -v '^\./profiles' |
		grep -v '^\./metadata' |
		grep -v '^\./scripts' ) ;
do
	echo cp -v "$name" "${CVS_PATH}/${name#./}"
done
